apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv2-ambulance-ufe-content
spec:
  microFrontend: cv2-ambulance-ufe
  element: cv2-ambulance-wl-app
  attributes:
    - name: base-path
      value: /cv2-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv2-ambulance-wl(/.*)?$"