apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv2-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /cv2-openapi
            - name: BASE_URL
              value: /cv2-openapi-ui